M48
; DRILL file {KiCad 8.0.6} date 2024-12-06T21:46:28+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-06T21:46:28+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.1575
%
G90
G05
T1
X5.5587Y-4.0142
X5.8087Y-3.9142
T2
X6.9685Y-3.8189
M30
