M48
; DRILL file {KiCad 8.0.6} date 2024-12-06T21:46:28+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-06T21:46:28+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1575
%
G90
G05
T1
X5.5087Y-4.1142
X5.9087Y-4.1142
T2
X5.7087Y-4.1142
M30
